events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-manager:8080;
    }

    upstream data_service {
        server data-collector:8080;
    }

    upstream prometheus_service {
        server prometheus:9090;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;
        server_name flight_manager.com localhost;
        return 308 https://$host:3443$request_uri;
    }

    server {
        listen              443 ssl;
        server_name         flight_manager.com localhost;

        ssl_certificate     /etc/nginx/certs/nginx-cert.pem;
        ssl_certificate_key /etc/nginx/certs/nginx-key.pem;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # --- USER MANAGER ROUTES ---
        location /users {
            proxy_pass http://user_service; 
        }
        location /docs/user {
            proxy_pass http://user_service;
        }
        location /schemas/user {
            proxy_pass http://user_service;
        }

        # --- DATA COLLECTOR ROUTES ---
        location /interests {
            proxy_pass http://data_service;
        }
        location /airports {
            proxy_pass http://data_service;
        }
        location /docs/data {
            proxy_pass http://data_service;
        }
        location /schemas/data {
            proxy_pass http://data_service;
        }

        # --- PROMETHEUS ROUTES ---
        location /prometheus/ {
            proxy_pass http://prometheus_service; 
        }
    }
}
