# Alert Notifier System

**Alert Notifier** is the final microservice in the pipeline, responsible for delivering notifications to users. It listens for alert events generated by the Alert System and handles the actual delivery mechanism.

The project is structured following the principles of **Hexagonal Architecture (Ports and Adapters)**.

## Project Structure

```plaintext
alert-notifier-system/
├── cmd/
│   └── main.go
├── config/
│   └── config.go
├── internal/
│   ├── adapters/
│   │   ├── kafka_consumer/
│   │   └── email_sender/
│   ├── application/
│   │   └── core/
│   │       ├── api/
│   │       └── domain/
│   └── ports/
│       └── service.go
├── Dockerfile
└── README.md
```

## Compass to Components

### 1\. The Core (Business Logic)

Everything residing here is agnostic regarding external technology.

| Directory | Description |
| :--- | :--- |
| `internal/application/core/domain` | **Pure Entities**. Fundamental data structures (`Notification` struct). |
| `internal/application/core/api` | **Service Layer**. Implements `NotifierService`. It prepares the notification content (Subject/Body) and orchestrates the sending process. |

### 2\. The Ports (Interfaces)

These define the interaction contracts between the Core and the outside world.

| File | Type | Description |
| :--- | :--- | :--- |
| `internal/ports/service.go` | **Input Port** | `NotifierService`: Defines the method to trigger a notification (`NotifyUser`). |
| `internal/ports/service.go` | **Output Port** | `EmailClient`: Defines the contract for sending the actual message (`SendEmail`). |

### 3\. The Adapters (Infrastructure)

Concrete implementations that communicate with the ports. This is where the division between **Driver** and **Driven** occurs.

| Directory | Role | Description |
| :--- | :--- | :--- |
| `adapters/kafka_consumer` | **Driver** | Listens to the `to-notifier` topic. When an alert arrives, it **invokes** the Core (`NotifyUser`). |
| `adapters/email_sender` | **Driven** | Implementation of `EmailClient`. Currently functions as a **Log Sender** (simulates email sending by printing to log). |
