// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialsRequest) Reset() {
	*x = VerifyCredentialsRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsRequest) ProtoMessage() {}

func (x *VerifyCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsRequest.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialsResponse) Reset() {
	*x = VerifyCredentialsResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsResponse) ProtoMessage() {}

func (x *VerifyCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsResponse.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCredentialsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type UserExistenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistenceRequest) Reset() {
	*x = UserExistenceRequest{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistenceRequest) ProtoMessage() {}

func (x *UserExistenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistenceRequest.ProtoReflect.Descriptor instead.
func (*UserExistenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserExistenceRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserExistenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistenceResponse) Reset() {
	*x = UserExistenceResponse{}
	mi := &file_pkg_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistenceResponse) ProtoMessage() {}

func (x *UserExistenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistenceResponse.ProtoReflect.Descriptor instead.
func (*UserExistenceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserExistenceResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_pkg_proto_user_user_proto protoreflect.FileDescriptor

const file_pkg_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/user/user.proto\x12\x04user\"L\n" +
	"\x18VerifyCredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"1\n" +
	"\x19VerifyCredentialsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\",\n" +
	"\x14UserExistenceRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"/\n" +
	"\x15UserExistenceResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xb2\x01\n" +
	"\vUserService\x12T\n" +
	"\x11VerifyCredentials\x12\x1e.user.VerifyCredentialsRequest\x1a\x1f.user.VerifyCredentialsResponse\x12M\n" +
	"\x12CheckUserExistence\x12\x1a.user.UserExistenceRequest\x1a\x1b.user.UserExistenceResponseB9Z7github.com/DanieleT25/FlightData-Manager/pkg/proto/userb\x06proto3"

var (
	file_pkg_proto_user_user_proto_rawDescOnce sync.Once
	file_pkg_proto_user_user_proto_rawDescData []byte
)

func file_pkg_proto_user_user_proto_rawDescGZIP() []byte {
	file_pkg_proto_user_user_proto_rawDescOnce.Do(func() {
		file_pkg_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_user_user_proto_rawDesc), len(file_pkg_proto_user_user_proto_rawDesc)))
	})
	return file_pkg_proto_user_user_proto_rawDescData
}

var file_pkg_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_user_user_proto_goTypes = []any{
	(*VerifyCredentialsRequest)(nil),  // 0: user.VerifyCredentialsRequest
	(*VerifyCredentialsResponse)(nil), // 1: user.VerifyCredentialsResponse
	(*UserExistenceRequest)(nil),      // 2: user.UserExistenceRequest
	(*UserExistenceResponse)(nil),     // 3: user.UserExistenceResponse
}
var file_pkg_proto_user_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.VerifyCredentials:input_type -> user.VerifyCredentialsRequest
	2, // 1: user.UserService.CheckUserExistence:input_type -> user.UserExistenceRequest
	1, // 2: user.UserService.VerifyCredentials:output_type -> user.VerifyCredentialsResponse
	3, // 3: user.UserService.CheckUserExistence:output_type -> user.UserExistenceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_user_proto_init() }
func file_pkg_proto_user_user_proto_init() {
	if File_pkg_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_user_proto_rawDesc), len(file_pkg_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_user_user_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_user_proto_depIdxs,
		MessageInfos:      file_pkg_proto_user_user_proto_msgTypes,
	}.Build()
	File_pkg_proto_user_user_proto = out.File
	file_pkg_proto_user_user_proto_goTypes = nil
	file_pkg_proto_user_user_proto_depIdxs = nil
}
