apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier
  namespace: flight-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier
  template:
    metadata:
      labels:
        app: alert-notifier
    spec:
      containers:
      - name: alert-notifier
        image: alert-notifier
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-env
        - secretRef:
            name: app-secrets
        env:
        - name: KAFKA_TOPIC
          value: "to-notifier"
        - name: KAFKA_GROUP_ID
          value: "alert-notifier-group"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
